"""Create User and Post tables

Revision ID: 2d2cbf0bb2e6
Revises: 6ae8b72508bd
Create Date: 2025-02-18 18:17:43.075210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2cbf0bb2e6'
down_revision: Union[str, None] = '6ae8b72508bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
